version: "3.9"

services:
  backend:
    build:
      context: .            # build context is the repo root
      dockerfile: backend/Dockerfile
    container_name: backend
    environment:
      - MODEL_PATH=/app/models/model.pkl
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/"]
      interval: 10s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
